### ISSUE TITLE
Closed group

### ISSUE THREAD

**Issue by abbbcccaa** [GuNsmoke12/facebook_diplomacy#1]
Hello, is there possibility to get feed from closed group?

**Comment by GuNsmoke12** [comment]
Hi there,
yes, but it's a bit complicated. That's actually what I am doing with this code, accessing the feed of a closed group so that another mate can see what is being posted.
The only thing you really need is a Facebook account that has access to the closed group, preferably the account is an admin of the group (I haven't tested using an account without admin privileges, but it might still work?).
Using this account there is two ways forward:
1) The quick and dirty way that I used. Generate an access token using the facebook account + facebook dev tools + facebook app, then use Facebook's Graph API. However, as far as I could tell Facebook no longer generates permanent access tokens (never expire), so the longest running token I could get was one that lasted 2 months. Once the token expires, you have to manually generate a new one and replace it in the code.
2) The better way is to use the Facebook Javascript SDK. Using the SDK you can build a sort of "auto-login" every time someone visits the webpage. This could then generate a new access token every time, thus you don't have to worry about the token expiring.

If you want to do some quick testing, you can just copy and paste all my HTML, CSS and JS. Then in the JS file, at the top, simply edit the variables "groupId" and "accessToken". Change them to your group's id, and generate your own access token to replace mine. There are several online guides which can help you with how to generate the appropriate access token.
